CREATE SCHEMA PALERMO_E_CASTELO;

use PALERMO_E_CASTELO;

CREATE TABLE TB_USERS(
    ID_USER INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    LOGIN VARCHAR(64) NOT NULL,
    PSSWORD VARCHAR(32) NOT NULL,
    DT_SUBMIT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE TB_PUBLICACOES_E_EVENTOS(
    ID_PUBLICATION INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    ID_USER INT NOT NULL,
    CONSTRAINT FK_ID_USER FOREIGN KEY (ID_USER) REFERENCES TB_USERS (ID_USER),
    TXT_DESCRIPTION VARCHAR(64) NOT NULL,
    TXT_TYPE VARCHAR(20) NOT NULL,
    TXT_CONTENT VARCHAR(500) NOT NULL,
    DT_CREATED TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    ID_LAWYER INT,
    CONSTRAINT FK_ID_LAWYER FOREIGN KEY (ID_LAWYER) REFERENCES TB_ADVOGADOS (ID_LAWYER)
);

CREATE TABLE TB_ADVOGADOS(
    ID_LAWYER INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    TXT_NAME VARCHAR(64) NOT NULL,
    NM_AGE INT NOT NULL,
    TXT_DESCRIPTION VARCHAR(25) NOT NULL,
    TXT_ATUATION VARCHAR(800) NOT NULL,
    TXT_EXPERIENCE VARCHAR(800) NOT NULL,
    TXT_GRADUATION VARCHAR(800) NOT NULL,
    TXT_LANGUAGE VARCHAR(500) NOT NULL,
    IMG_PATH VARCHAR (256) NOT NULL,
    TXT_EMAIL VARCHAR(64),
    TXT_TEL VARCHAR(20),
    TXT_CEL VARCHAR(20),
    DT_CREATED TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE TB_CONTATO(
    ID_CONTACT INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    DT_SENDED TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    TXT_NAME VARCHAR (64) NOT NULL,
    NM_TEL INT,
    TXT_EMAIL VARCHAR(64) NOT NULL,
    TXT_SUBJECT VARCHAR(128),
    TXT_MESSAGE VARCHAR(500) NOT NULL,
    BL_VISUALIZED BOOLEAN NOT NULL,
    UP_FILE LONGBLOB NOT NULL
);

CREATE TABLE TB_NEWSLETTER(
    ID_REGISTRY INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    DT_REGISTRY TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    TXT_NAME VARCHAR (64) NOT NULL,
    TXT_EMAIL VARCHAR(64) NOT NULL,
    BL_ACTIVE BOOLEAN NOT NULL
);

CREATE TABLE TB_LANGUAGE(
    TXT_KEY VARCHAR(64) NOT NULL PRIMARY KEY,
    TXT_VALUE TEXT NOT NULL,
    TXT_LANG VARCHAR(2) NOT NULL,
    DT_INSERTED TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP()
);


DROP TABLE TB_PUBLICACOES_E_EVENTOS;

DROP TABLE TB_ADVOGADOS;

DROP TABLE TB_USERS;

DROP TABLE TB_CONTATO;

INSERT INTO TB_USERS (LOGIN, PSSWORD) VALUES ("root", "admin_palermo");
INSERT INTO TB_USERS (LOGIN, PSSWORD) VALUES ("root", md5("root"));|

INSERT INTO TB_PUBLICACOES_E_EVENTOS(ID_USER, TXT_DESCRIPTION, TXT_TYPE, TXT_CONTENT, DT_CREATED) VALUES (1, "Olá", "Anuncio", "Isso é um teste", 25/07/2017);
INSERT INTO TB_PUBLICACOES_E_EVENTOS(ID_USER, TXT_DESCRIPTION, TXT_TYPE, TXT_CONTENT, DT_CREATED) VALUES (1, "Olá", "Anuncio", "Isso é um teste", STR_TO_DATE("25/07/2017", "%d/%m/%Y"));

CREATE USER 'dev'@'165.227.90.115' IDENTIFIED BY 'DevPssword@2017';

GRANT ALL PRIVILEGES ON * . * TO 'root'@'165.227.90.115';

FLUSH PRIVILEGES;

GRANT ALL ON PALERMO_E_CASTELO.* TO @'165.227.90.115' IDENTIFIED BY 'DevPssword@2017';


CREATE USER 'wp-user'@localhost IDENTIFIED BY 'WordPress@9';

GRANT ALL PRIVILEGES ON csorgo_wordpress.* TO 'wp-user'@localhost;
FLUSH PRIVILEGES;

DELETE FROM TB_ADVOGADOS WHERE ID_LAWYER = 39;

INSERT INTO TB_ADVOGADOS (ID_LAWYER, TXT_NAME,NM_AGE,TXT_DESCRIPTION,TXT_ATUATION,TXT_EXPERIENCE,TXT_GRADUATION,TXT_LANGUAGE,IMG_PATH,TXT_EMAIL,TXT_TEL,TXT_CEL) VALUES (38, "Dra Marcia", 38, "Advogada", "Atuacao", "Experiencia", "Graduacao", "Idiomas", "/../imagens-advogados/r_lawyer_014.jpg", "mariana.pontes@palermoecastelo.com.br", "(11) 9999-9999", "(11) 9999-9999");