CREATE SCHEMA PALERMO_E_CASTELO;

USE PALERMO_E_CASTELO;

CREATE TABLE TB_USERS(
    ID_USER INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    LOGIN VARCHAR(64) NOT NULL,
    PSSWORD VARCHAR(32) NOT NULL,
    DT_SUBMIT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE TB_PUBLICACOES_E_EVENTOS(
    ID_PUBLICATION INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    ID_USER INT NOT NULL,
    CONSTRAINT FK_ID_USER FOREIGN KEY (ID_USER) REFERENCES TB_USERS (ID_USER),
    TXT_DESCRIPTION VARCHAR(64) NOT NULL,
    TXT_TYPE VARCHAR(20) NOT NULL,
    TXT_CONTENT VARCHAR(500) NOT NULL,
    DT_CREATED TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE TB_ADVOGADOS(
    ID_LAWYER INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    TXT_NAME VARCHAR(64) NOT NULL,
    NM_AGE INT NOT NULL,
    TXT_DESCRIPTION VARCHAR(60) NOT NULL,
    PIC_IMAGE LONGBLOB NOT NULL
);

/* CREATE TABLE TB_FILE(
    ID_FILE INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    DT_SENDED TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    TXT_TMP_NAME VARCHAR(128) NOT NULL,
    TXT_SIZE VARCHAR(128) NOT NULL,
    TXT_TYPE VARCHAR(128) NOT NULL,
    TXT_FILE_NAME VARCHAR(256) NOT NULL
); 
*/

CREATE TABLE TB_CONTATO(
    ID_CONTACT INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    DT_SENDED TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    TXT_NAME VARCHAR (64) NOT NULL,
    NM_TEL INT,
    TXT_EMAIL VARCHAR(64) NOT NULL,
    TXT_SUBJECT VARCHAR(128),
    TXT_MESSAGE VARCHAR(500) NOT NULL,
    BL_VISUALIZED BOOLEAN NOT NULL,
    UP_FILE LONGBLOB NOT NULL
);

CREATE TABLE TB_NEWSLETTER(
    ID_REGISTRY INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    DT_REGISTRY TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    TXT_NAME VARCHAR (64) NOT NULL,
    TXT_EMAIL VARCHAR(64) NOT NULL,
    BL_ACTIVE BOOLEAN NOT NULL
);

CREATE TABLE TB_LANGUAGE(
    TXT_KEY VARCHAR(64) NOT NULL PRIMARY KEY,
    TXT_VALUE TEXT NOT NULL,
    TXT_LANG VARCHAR(2) NOT NULL,
    DT_INSERTED TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP()
);


INSERT INTO TB_LANGUAGE (TXT_KEY, TXT_VALUE, TXT_LANG) VALUES ("MENU_NAVBAR_TITLE_OFFICE", "O ESCRITÓRIO", "pt");
INSERT INTO TB_LANGUAGE (TXT_KEY, TXT_VALUE, TXT_LANG) VALUES ("MENU_NAVBAR_TITLE_OFFICE_HISTORY", "HISTÓRICO", "pt");
INSERT INTO TB_LANGUAGE (TXT_KEY, TXT_VALUE, TXT_LANG) VALUES ("MENU_NAVBAR_TITLE_OFFICE_ABOUTUS", "QUEM SOMOS", "pt");
INSERT INTO TB_LANGUAGE (TXT_KEY, TXT_VALUE, TXT_LANG) VALUES ("MENU_NAVBAR_TITLE_OFFICE_MISSION", "MISSÃO", "pt");
INSERT INTO TB_LANGUAGE (TXT_KEY, TXT_VALUE, TXT_LANG) VALUES ("MENU_NAVBAR_TITLE_LAWYER", "ADVOGADOS", "pt");
INSERT INTO TB_LANGUAGE (TXT_KEY, TXT_VALUE, TXT_LANG) VALUES ("MENU_NAVBAR_TITLE_ACTUATION", "ÁREAS DE ATUAÇÃO", "pt");
INSERT INTO TB_LANGUAGE (TXT_KEY, TXT_VALUE, TXT_LANG) VALUES ("MENU_NAVBAR_TITLE_PUBLICATION", "PUBLICAÇÕES E EVENTOS", "pt");
INSERT INTO TB_LANGUAGE (TXT_KEY, TXT_VALUE, TXT_LANG) VALUES ("MENU_NAVBAR_TITLE_CONTACT", "CONTATO", "pt");

INSERT INTO TB_LANGUAGE (TXT_KEY, TXT_VALUE, TXT_LANG) VALUES (value1, value2, value3);
INSERT INTO TB_LANGUAGE (TXT_KEY, TXT_VALUE, TXT_LANG) VALUES (value1, value2, value3);
INSERT INTO TB_LANGUAGE (TXT_KEY, TXT_VALUE, TXT_LANG) VALUES (value1, value2, value3);
INSERT INTO TB_LANGUAGE (TXT_KEY, TXT_VALUE, TXT_LANG) VALUES (value1, value2, value3);
INSERT INTO TB_LANGUAGE (TXT_KEY, TXT_VALUE, TXT_LANG) VALUES (value1, value2, value3);
INSERT INTO TB_LANGUAGE (TXT_KEY, TXT_VALUE, TXT_LANG) VALUES (value1, value2, value3);
INSERT INTO TB_LANGUAGE (TXT_KEY, TXT_VALUE, TXT_LANG) VALUES (value1, value2, value3);
INSERT INTO TB_LANGUAGE (TXT_KEY, TXT_VALUE, TXT_LANG) VALUES (value1, value2, value3);
INSERT INTO TB_LANGUAGE (TXT_KEY, TXT_VALUE, TXT_LANG) VALUES (value1, value2, value3);
INSERT INTO TB_LANGUAGE (TXT_KEY, TXT_VALUE, TXT_LANG) VALUES (value1, value2, value3);
INSERT INTO TB_LANGUAGE (TXT_KEY, TXT_VALUE, TXT_LANG) VALUES (value1, value2, value3);
INSERT INTO TB_LANGUAGE (TXT_KEY, TXT_VALUE, TXT_LANG) VALUES (value1, value2, value3);
INSERT INTO TB_LANGUAGE (TXT_KEY, TXT_VALUE, TXT_LANG) VALUES (value1, value2, value3);
INSERT INTO TB_LANGUAGE (TXT_KEY, TXT_VALUE, TXT_LANG) VALUES (value1, value2, value3);
INSERT INTO TB_LANGUAGE (TXT_KEY, TXT_VALUE, TXT_LANG) VALUES (value1, value2, value3);
INSERT INTO TB_LANGUAGE (TXT_KEY, TXT_VALUE, TXT_LANG) VALUES (value1, value2, value3);
INSERT INTO TB_LANGUAGE (TXT_KEY, TXT_VALUE, TXT_LANG) VALUES (value1, value2, value3);
INSERT INTO TB_LANGUAGE (TXT_KEY, TXT_VALUE, TXT_LANG) VALUES (value1, value2, value3);
INSERT INTO TB_LANGUAGE (TXT_KEY, TXT_VALUE, TXT_LANG) VALUES (value1, value2, value3);
INSERT INTO TB_LANGUAGE (TXT_KEY, TXT_VALUE, TXT_LANG) VALUES (value1, value2, value3);
INSERT INTO TB_LANGUAGE (TXT_KEY, TXT_VALUE, TXT_LANG) VALUES (value1, value2, value3);
INSERT INTO TB_LANGUAGE (TXT_KEY, TXT_VALUE, TXT_LANG) VALUES (value1, value2, value3);
INSERT INTO TB_LANGUAGE (TXT_KEY, TXT_VALUE, TXT_LANG) VALUES (value1, value2, value3);
INSERT INTO TB_LANGUAGE (TXT_KEY, TXT_VALUE, TXT_LANG) VALUES (value1, value2, value3);
